more convention enforcement

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -1,33 +1,4 @@
-name: java-platform
-on:
-  pull_request:
-    branches:
-      - master
-  push:
-    branches:
-      - master
-  workflow_dispatch: {}
-jobs:
-  property-validation:
-    env:
-      pattern: '^REL\.[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{4}$'
-    name: ci tests
-    runs-on: ubuntu-20.04
-    steps:
-      - name: Setup Maven Action
-        uses: s4u/setup-maven-action@v1.6.0
-        with:
-          java-version: 8
-
-      - name: Validate tealium.platform.limits.consumer property
-        working-directory: all_modules
-        run: |
-          version=$(mvn help:evaluate \
-            -Dexpression=tealium.platform.limits.consumer -q -DforceStdout)
-          echo "VERSION: $version"
-          echo $version | grep -Eq '${{ env.pattern }}'
-
-name: Update Tags
+name: gha action ci
 
 on:
   push:
@@ -63,6 +34,10 @@ jobs:
           fi
           if [ ! -f "$action/README.md" ]; then
             echo "ERROR: $action/README.md not found."
+            exit 1
+          fi
+          if [ ! -f "$action/action.yaml" ]; then
+            echo "ERROR: $action/action.yaml does not exist."
             exit 1
           fi
         done
