explicit exit handling

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -30,7 +30,18 @@ jobs:
     - name: Determine Changed Actions
       id: changed_actions
       run: |
-        CHANGED_ACTIONS=$(git diff --name-only '${{ github.event.before }}' '${{ github.sha }}' | awk -F '/' '{print $1}' | uniq) && \
+        git fetch --depth=1 origin ${{ github.ref }}
+        git diff --name-only '${{ github.event.before }}' '${{ github.sha }}' \
+          | awk -F '/' '{print $1}' \
+          | uniq > ./changed_actions.txt
+        
+        exit_code=$?
+        if [ $exit_code -ne 0 ]; then
+          echo "ERROR: Git diff command failed with exit code $exit_code."
+          exit $exit_code
+        fi
+
+        CHANGED_ACTIONS=$(cat ./changed_actions.txt) && \
         echo "changed_actions=${CHANGED_ACTIONS}" >> $GITHUB_ENV
 
     - name: Verify Version Update and README.md Presence
